### ISSUE TITLE
Semantic versioning for the gem?

### ISSUE THREAD

**Issue by AlexVPopov** [freego/js_cookie_rails#2]
I would like to suggest that the gem version track the gemified library version. In this case that would be 2.0.3. If changes are made, that do not directly affect the code of the library, than a fourth number can be added. For reference, please check:
- [Gemify Assets for Rails](http://www.prioritized.net/blog/gemify-assets-for-rails/), section Versioning
- [momentjr-rails](https://github.com/derekprior/momentjs-rails#versioning)

Would you accept such a PR?

**Comment by alepore** [comment]
Sure, good idea.
I can also add you to the repo if you want, let me know

**Comment by AlexVPopov** [comment]
O.K., I will make the PR. Sure thing about the repo.

**Comment by alepore** [comment]
:+1: repo and rubygems access
