### ISSUE TITLE
.Cookie is not a funciton TypeError

### ISSUE THREAD

**Issue by radmanmm** [freego/js_cookie_rails#5]

**Comment by Schwad** [comment]
I've got the same issue here, I reckon what happened is this gent was trying to upgrade from jquery-cookie-rails like I'm attempting to do right now.

**Comment by mayuresh-srivastava** [comment]
Got the same on Rails upgrade to 5.2, just had to change `$.cookie` to `Cookies` & `$.removeCookie` to `Cookies.remove` as documented [here](https://github.com/js-cookie/js-cookie)
